### ISSUE TITLE
APIView.headers type is missing

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/djangorestframework-stubs#76]
This line show that there's `headers` field in `APIView` class: https://github.com/encode/django-rest-framework/blob/5ce237e00471d885f05e6d979ec777552809b3b1/rest_framework/views.py#L494

Currently it is missing.

Related #74 and #75

**Comment by Goldziher** [comment]
Should be resolved, no?

**Comment by sobolevn** [comment]
It is still `Any`. Let's keep it in case someone might fix them to be more specific later.

**Comment by MarcinWieczorek** [comment]
`default_response_headers` is a `Dict[str, str]` as introduced in 9f49d5aa15d071f39547b630b30fbd376fec27ee. I think `APIView.headers` should be that too because of the default value. Those are HTTP headers which are text in the end and I'm not familiar with any usecases of passing anything but str to headers in django or drf.

**Comment by sobolevn** [comment]
@MarcinWieczorek PRs are welcome!

**Comment by MarcinWieczorek** [comment]
Sure, if you agree with that changing that to `Dict[str, str]` I'll do that soon.
